---
- name: check ruby-build installed
  command: test -x /usr/local/bin/ruby-build
  register: rbuild_present
  ignore_errors: yes
  changed_when: false

- name: create temporary directory
  command: mktemp -d
  register: tempdir
  when: rbuild_present|failed

- name: clone ruby-build repo
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "{{ tempdir.stdout }}/ruby-build"
    update: no
  when: rbuild_present|failed

- name: install ruby-build
  sudo: true
  args:
    chdir: {{ tempdir.stdout }}/ruby-build
  command: ./install.sh
  when: rbuild_present|failed

- name: remove temporary directory
  file:
    path: "{{ tempdir.stdout }}"
    state: absent
  when: rbuild_present|failed
