---
- name: apt-get update
  sudo: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install build depends
  sudo: true
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - build-essential
    - git
